export const PROFILE_MENU_TAB_USER = "User";
export const PROFILE_MENU_TAB_WORKSHOPS = "Workshops";
export const PROFILE_MENU_TAB_EVENTS = "Events";
export const PROFILE_MENU_TAB_PRODUCTS = "Products";

export const PROFILE_MENU_TABS = [
  PROFILE_MENU_TAB_USER,
  PROFILE_MENU_TAB_WORKSHOPS,
  PROFILE_MENU_TAB_EVENTS,
  PROFILE_MENU_TAB_PRODUCTS,
] as const;
